### ISSUE TITLE
Refactor to use GHA provided go

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/func-e#378]
**Is your feature request related to a problem? Please describe.**
Right now, we have to wait for go installs using setup-go even when the host already has go on it.

**Describe the solution you'd like**
I'd like to take advantage of files already on disk. Ex.

```yaml
# Use the built-in latest patch of go to save install time
# Ex. https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#environment-variables-2
env:
  GOROOT: GOROOT_1_17_X64
  CONFIGURE_GO: |  # Note: We can't interpolate ${{ env.GOROOT }} here, hence repetition.
    echo "GOROOT=$GOROOT_1_17_X64" >> $GITHUB_ENV
    echo "$GOROOT_1_17_X64/bin" >> $GITHUB_PATH

--snip--
      - name: "Configure Go"
        run: ${{ env.CONFIGURE_GO }}
--snip--
          key: test-${{ runner.os }}-${{ env.GOROOT }}-go-${{ hashFiles('go.sum', 'Makefile') }}
```

Note: this would only apply out-of-box with config managed by GitHub Actions. For example, our internal docker images don't currently cache the same way. Also there's inconsistency in how macos is handled, which is making it less ideal until sorted somehow.

**Describe alternatives you've considered**
not doing this and just dealing with it

**Additional context**
env variables don't yet exist for macos https://github.com/actions/virtual-environments/issues/4156
we still need to cache the current versions on our internal docker images
